steps:
  - id: "Generate UI App Version"
    name: node
    entrypoint: bash
    args:
      - -c
      - |
        # Save package.json app version to persistent volume mount: "/workspace"
        echo $(node -p -e "require('./package.json').version") > /workspace/app_version.txt
  - id: "Build Web Container"
    name: "gcr.io/cloud-builders/docker"
    entrypoint: "sh"
    args:
      - -c
      - |
        cd ui/
        echo $(cat ../app_version.txt)
        docker build -t gcr.io/${_PROJECT_ID}/${$BRANCH_NAME}/${_ENV}/shifter-ui:$(cat ../app_version.txt) -t gcr.io/${_PROJECT_ID}/${$BRANCH_NAME}/${_ENV}/shifter-ui:latest .
        docker push gcr.io/${_PROJECT_ID}/${$BRANCH_NAME}//${_ENV}/shifter-ui:$(cat ../app_version.txt)
        docker push gcr.io/${_PROJECT_ID}/${$BRANCH_NAME}//${_ENV}/shifter-ui:latest